databases:
  - name: AmitCoaching
    databaseName: AmitCoaching_production
    user: rails
    plan: free

services:
  - type: web
    name: AmitCoaching_web
    runtime: ruby
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AmitCoaching_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 